corteva/geocube

.travis.yml
appveyor.yml
environment.yml
setup.py

remove datacube pin

---

.travis.yml
appveyor.yml
geocube/rasterize.py
setup.py
sphinx/history.rst
test/integration/api/test_core_integration.py

Add merge algorithm option for rasterization & drop python 2 support

---

geocube/cli/commands/make_geocube.py
geocube/geo_utils/geobox.py
geocube/rasterize.py
sphinx/history.rst
test/integration/api/test_core_integration.py
test/unit/cli/commands/test_make_geocube.py

Note: removed `autoclose=True` as it is deprecated.

add rescale kwarg to rasterize_points_griddata; fix for compatibility with geopandas 0.6

---

Makefile
geocube/cli/geocube.py
geocube/geo_utils/geobox.py
geocube/rasterize.py
geocube/vector_to_cube.py
setup.py
sphinx/conf.py
sphinx/history.rst
test/integration/api/test_core_integration.py

Drop python 3.5 support

---

.travis.yml

Related to https://github.com/corteva/rioxarray/issues/108

Pin conda version in travis for stability

---

test/integration/api/test_core_integration.py

xfail for custom rasterize function conitional to scipy version

---

docs/history.rst
geocube/vector_to_cube.py
setup.py

Address deprecation warnings from datacube and rioxarray

---

docs/examples/categorical.ipynb
geocube/api/core.py
geocube/vector_to_cube.py

DOC: Add note that the categories will be made unique and sorted.

---

.travis.yml
CONTRIBUTING.rst
appveyor.yml
setup.py

- Windows failure with Python 3.6 related to: https://github.com/conda-forge/fiona-feedstock/issues/171. Upgraded to 3.7 and it works now.
- Disabled 3.9 in Travis due to conda installation issues. Will try enabling in the future.

Update DOC and CI for Python 3.6-3.9

---

.isort.cfg
geocube/xarray_extensions/vectorxarray.py
setup.py
test/integration/xarray_extensions/test_integration_xarray_extensions_vectorxarray.py

Address xarray & numpy deprecations

---

docs/history.rst
geocube/geo_utils/geobox.py

BUG: Compatibility with rioxarray 0.3

---

LICENSE

Update license year to 2021

---

.github/workflows/build_docs.yaml
.github/workflows/tests.yaml
appveyor.yml

Related: https://github.com/corteva/rioxarray/pull/384

CI: Use strict conda channel priority for installation

---

geocube/geo_utils/geobox.py
setup.py
test/integration/api/test_core_integration.py

https://www.python.org/dev/peps/pep-0632/

DEP: Replace distutils with packaging

---

.github/workflows/tests.yaml
CONTRIBUTING.rst
appveyor.yml
docs/history.rst
environment.yml
setup.py

DEP: Drop Python 3.7 Support

---

geocube/geo_utils/geobox.py

Changes width and height order to the one used in rioxarray

---

.github/workflows/build_docs.yaml
.github/workflows/tests.yaml
appveyor.yml
docs/getting_started.rst
environment.yml
geocube/_show_versions.py
geocube/geo_utils/geobox.py
geocube/rasterize.py
setup.py
test/unit/test_show_versions.py

REF: Replace datacube with odc-geo

---

mypy.ini

https://github.com/opendatacube/odc-geo/pull/37

TYPE: Remove odc-geo skip missing imports

---

docs/history.rst
geocube/geo_utils/geobox.py
test/unit/geo_utils/test_unit_geo_utils_geobox.py

Related: https://github.com/opendatacube/odc-geo/pull/41/

BUG: Handle input CRS without EPSG

---

geocube/rasterize.py
geocube/vector_to_cube.py

Ran into import issues using this syntax with other libraries.

TYPE: Modified NDArray import for typing

---

.flake8
.pre-commit-config.yaml

https://github.com/corteva/geocube/actions/runs/4272785137/jobs/7438229644

LNT: Update pre-commit pins

---

.github/workflows/build_docs.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
CONTRIBUTING.rst
appveyor.yml
docs/history.rst
environment.yml
mypy.ini
setup.cfg

DEP: Drop Python 3.8 Support

---

geocube/api/core.py
geocube/cli/commands/__init__.py
geocube/cli/commands/make_geocube.py
geocube/cli/geocube.py
geocube/geo_utils/__init__.py
geocube/geo_utils/geobox.py
geocube/rasterize.py
geocube/vector_to_cube.py
geocube/xarray_extensions/vectorxarray.py

Related: #136
```
pyupgrade --py39-plus `find . -name "*.py" -type f`
```

REF: Upgrade to Python 3.9+ codestyle

---

docs/history.rst
geocube/vector_to_cube.py
test/integration/api/test_core_integration.py
test/test_data/input/naive_time_vector_data.geojson

BUG: Fix conversion to datetime64[ns] for naive datetimes

---

.github/workflows/release.yaml

https://github.com/pypa/twine/issues/1125

MNT: Avoid broken twine version
